# Generated by Django 4.1.1 on 2022-10-07 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='taskCompleted',
            field=models.BooleanField(default=False),
        ),
    ]
